src/Entity/Image.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\File;

/**
 * Class Image
 *
 * @author Olivier Maréchal <o.marechal@icloud.com>
 *
 * @ORM\Entity
 * @Vich\Uploadable
 */
class Image
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string")
     */
    private $filename;

    /**
     * @Vich\UploadableField(mapping="files", fileNameProperty="filename")
     */
    private $image;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updatedAt;

    /**
     * @ORM\ManyToOne(targetEntity="BodyWorkFolio", inversedBy="afters")
     */
    private $bodyWorkAfter;

    /**
     * @ORM\ManyToOne(targetEntity="BodyWorkFolio", inversedBy="befores")
     */
    private $bodyWorkBefore;

    /**
     * @ORM\ManyToOne(targetEntity="MecanicFolio", inversedBy="images")
     */
    private $mecanic;

    /**
     * Image Constructor
     */
    public function __construct()
    {
        $this->createdAt = new \DateTime();
    }

    /**
     * Image ToString
     */
    public function __toString()
    {
        return $this->filename ?: '';
    }

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param string $filename
     *
     * @return Image
     */
    public function setFilename($filename)
    {
        $this->filename = $filename;

        return $this;
    }

    /**
     * @return string
     */
    public function getFilename()
    {
        return $this->filename;
    }

    /**
     * @param File $image
     *
     * @return Image
     */
    public function setImage(File $image)
    {
        $this->image = $image;

        if ($image) {
            $this->updatedAt = new \DateTime();
        }

        return $this;
    }

    /**
     * @return File
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * @param \DateTime $createdAt
     *
     * @return Image
     */
    public function setCreatedAt(\DateTime $createdAt = null)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * @param \DateTime $updatedAt
     *
     * @return Image
     */
    public function setUpdatedAt(\DateTime $updatedAt = null)
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return string
     */
    public function getPathImage()
    {
        return '/upload/'.$this->filename;
    }

    /**
     * @return BodyWorkFolio
     */
    public function getBodyWorkBefore()
    {
        return $this->bodyWorkBefore;
    }

    /**
     * @param BodyWorkFolio $before
     *
     * @return Image
     */
    public function setBodyWorkBefore(BodyWorkFolio $before = null)
    {
        $this->bodyWorkBefore = $before;

        return $this;
    }

    /**
     * @return BodyWorkFolio
     */
    public function getBodyWorkAfter()
    {
        return $this->bodyWorkAfter;
    }

    /**
     * @param BodyWorkFolio $after
     *
     * @return Image
     */
    public function setBodyWorkAfter(BodyWorkFolio $after = null)
    {
        $this->bodyWorkAfter = $after;

        return $this;
    }

    /**
     * @return MecanicFolio
     */
    public function getMecanic()
    {
        return $this->mecanic;
    }

    /**
     * @param Mecanic $mecanic
     *
     * @return Image
     */
    public function setMecanic(MecanicFolio $mecanic = null)
    {
        $this->mecanic = $mecanic;

        return $this;
    }
}

src/Controller/BodyWorkController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;
use App\Entity\BodyWorkFolio;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;

/**
 * Class BodyWorkController
 *
 * @author Olivier Maréchal <o.marechal@icloud.com>
 */
class BodyWorkController extends Controller
{
    /**
     * @Route("/carrosserie", name="bodywork_index")
     */
    public function indexAction(EntityManagerInterface $em)
    {
        $bodyWorksFolio = $em->getRepository(BodyWorkFolio::class)->getLastWithLimit(3);

        return $this->render('body_work/index.html.twig', ['bodyWorks' => $bodyWorksFolio]);
    }

    /**
     * @Route("/carrosserie/portfolio", name="bodywork_folio")
     */
    public function portfolioAction(Request $request, EntityManagerInterface $em)
    {
        $qb = $em->getRepository(BodyWorkFolio::class)->getQueryAll();
        $adapter = new DoctrineORMAdapter($qb);
        $pagerfanta = new Pagerfanta($adapter);
        $pagerfanta->setMaxPerPage(10);
        $pagerfanta->setCurrentPage($request->get('page', 1));

        return $this->render('body_work/portfolio.html.twig', [
            'pager' => $pagerfanta
        ]);
    }
}

templates/body_work/body_work_card.html.twig
<div class="indent-left">
    <h3>{{ bodyWork.name }}</h3>
    <p>{{ bodyWork.description }}</p>
    <div class="indent-left">
    <h6>Avant</h6>
        <div>
            {% for imageBefore in bodyWork.befores %}
                <a class="fancybox" href="{{ asset(imageBefore.pathImage) }}" data-fancybox="before" /><img src="{{ asset(imageBefore.pathImage) }}" width="300"/></a>
            {% endfor %}
        </div>
    </div>
    <div class="indent-left">
        <h6>Après</h6>
        <div>
            {% for imageAfter in bodyWork.afters %}
                <a class="fancybox" href="{{ asset(imageAfter.pathImage) }}" data-fancybox="after" /><img src="{{ asset(imageAfter.pathImage) }}" width="300"/></a>
            {% endfor %}
        </div>
    </div>
</div>

templates/body_work/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container-bot">
        <div class="container-top">
            <div class="container">
                <div class="wrapper">
                    <article class="grid_8">
                        <div class="indent-left">
                            <h2>Carrosserie/Peinture</h2>
                            <p class="prev-indent-bot">DB Auto Pneus vous propose la <strong>Carrosserie</strong> de vos vehicules accidentés, vandalisés, rayés, notre carrossier démontera les éléments endommagés, il va remettre en forme ceux qui sont réparables et remplacera ceux qui sont irrécupérables. </p>
                            <p class="border-bot">Il prépare ensuite le véhicule en améliorant la qualité de la surface (masticage, ponçage...). Enfin, après avoir protégé les parties intactes, il peut appliquer la peinture au pistolet, effectuer les retouches et les finitions.</p>
                        </div>
                    </article>
                </div>
            </div>
        </div>
    </div>

    {% for bodyWork in bodyWorks %}
        {% include 'body_work/body_work_card.html.twig' with {'bodyWork': bodyWork} %}
    {% endfor %}
    <a href="{{ path('bodywork_folio') }}">voir plus</a>

    <div class="container-bot">
        <div class="container-top">
            <div class="container">
                <div class="wrapper">
                    <article class="grid_8">
                        <div class="indent-left">
                            <h2>Informations</h2>
                            <p class="prev-indent-bot">DB Auto pneus Saint-Savournin offre pour toutes préstations de carrosserie la franchise de votre assureur ainsi qu'un nettoyage complet de votre vehicule.</p>
                            <p class="border-bot">Vous souhaitez un devis? Une information supplémentaire ? N'hesitez pas à contacter notre garage qui se fera un plaisir de vous renseigner.</p>
                        </div>
                    </article>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
    

templates/body_work/portfolio.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% for bodyWork in pager.currentPageResults %}
        {% include 'body_work/body_work_card.html.twig' with {'bodyWork': bodyWork} %}
    {% endfor %}

    {% if pager.nbPages > 1 %}
        {% for page in 1..pager.nbPages %}
            {% if page == pager.currentPage %}
                {{ page }}
            {% else %}
                <a href="{{ path('bodywork_folio', {'page': page }) }}">{{ page }}</a>
            {% endif %}
        {% endfor %}
    {% endif %}
{% endblock %}